# Supported funding platforms: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: kaovilai
custom:
  - https://paypal.me/pkaov
  - https://venmo.com/code?user_id=2065666886598656219
  - https://cash.me/$tigpk
  - https://m.me/passawit
