#!/bin/bash
set -euo pipefail

# Shared utilities
# shellcheck source=lib-common.sh
source "$(dirname "$0")/lib-common.sh"

OUTPUT_FILE="MY_ACTIVITY.md"

# JSON output for structured consumption (e.g. kaovilai.pw)
JSON_OUTPUT_FILE="activity.json"

CURRENT_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
GENERATED_AT_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)
TODAY=$(date -u +%Y-%m-%d)
NINETY_DAYS_AGO=$(date -u -d '90 days ago' +%Y-%m-%d 2>/dev/null || date -u -v-90d +%Y-%m-%d)

# Org grouping helper: takes JSON array, groups by org, outputs markdown
group_by_org() {
    local json="$1"
    local orgs=("velero-io" "openshift" "migtools" "oadp-rebase")
    local count
    count=$(echo "$json" | jq 'length')

    if [ "$count" -eq 0 ]; then
        echo "No activity."
        echo ""
        return
    fi

    for org in "${orgs[@]}"; do
        local org_items
        org_items=$(echo "$json" | jq -c --arg org "$org" '[.[] | select(.repository.nameWithOwner | startswith($org + "/"))]')
        local org_count
        org_count=$(echo "$org_items" | jq 'length')

        if [ "$org_count" -gt 0 ]; then
            echo "**$org** ($org_count)"
            echo "$org_items" | jq -r '.[] | "- [#\(.number) \(.title)](\(.url)) — \(.repository.nameWithOwner)"'
            echo ""
        fi
    done

    # Others
    local other_items
    other_items=$(echo "$json" | jq -c '[.[] | select(.repository.nameWithOwner | (startswith("velero-io/") or startswith("openshift/") or startswith("migtools/") or startswith("oadp-rebase/")) | not)]')
    local other_count
    other_count=$(echo "$other_items" | jq 'length')

    if [ "$other_count" -gt 0 ]; then
        echo "**Other** ($other_count)"
        echo "$other_items" | jq -r '.[] | "- [#\(.number) \(.title)](\(.url)) — \(.repository.nameWithOwner)"'
        echo ""
    fi
}

echo "Generating activity log for $NINETY_DAYS_AGO to $CURRENT_DATE..."

# Fetch all data
echo "Fetching merged PRs..."
MERGED_PRS=$(retry_with_backoff gh search prs is:public --author=kaovilai --merged --merged-at=">=$NINETY_DAYS_AGO" \
    --json number,title,repository,url,closedAt --sort=updated --limit 100)

echo "Fetching opened PRs..."
OPENED_PRS=$(retry_with_backoff gh search prs is:public --author=kaovilai --created=">=$NINETY_DAYS_AGO" \
    --json number,title,repository,url,isDraft,state,createdAt --sort=created --limit 100)

echo "Fetching PRs reviewed..."
REVIEWED_PRS=$(retry_with_backoff gh search prs is:public --reviewed-by=kaovilai --sort=updated --created=">=$NINETY_DAYS_AGO" \
    --json number,title,repository,url,author,updatedAt --limit 100)
# Exclude own PRs from reviews
REVIEWED_PRS=$(echo "$REVIEWED_PRS" | jq -c '[.[] | select(.author.login != "kaovilai")]')

echo "Fetching PRs/issues commented on..."
COMMENTED=$(retry_with_backoff gh search issues is:public --commenter=kaovilai --updated=">=$NINETY_DAYS_AGO" \
    --json number,title,repository,url,updatedAt --sort=updated --limit 100)
# Exclude own issues/PRs
COMMENTED=$(echo "$COMMENTED" | jq -c '[.[] | select(true)]')

echo "Fetching issues closed..."
CLOSED_ISSUES=$(retry_with_backoff gh search issues is:public --author=kaovilai --state=closed --closed=">=$NINETY_DAYS_AGO" \
    --json number,title,repository,url,closedAt --sort=updated --limit 100)

# Count totals
MERGED_COUNT=$(echo "$MERGED_PRS" | jq 'length')
OPENED_COUNT=$(echo "$OPENED_PRS" | jq 'length')
REVIEWED_COUNT=$(echo "$REVIEWED_PRS" | jq 'length')
COMMENTED_COUNT=$(echo "$COMMENTED" | jq 'length')
CLOSED_COUNT=$(echo "$CLOSED_ISSUES" | jq 'length')

# Generate report
cat > "$OUTPUT_FILE" << EOF
# Activity Log

> **Period:** $NINETY_DAYS_AGO — $(date -u +%Y-%m-%d)
> **Generated:** $CURRENT_DATE

| Metric | Count |
|--------|-------|
| PRs Merged | $MERGED_COUNT |
| PRs Opened | $OPENED_COUNT |
| PRs Reviewed | $REVIEWED_COUNT |
| Issues/PRs Commented | $COMMENTED_COUNT |
| Issues Closed | $CLOSED_COUNT |

---

## PRs Merged ($MERGED_COUNT)

$(group_by_org "$MERGED_PRS")
## PRs Opened ($OPENED_COUNT)

$(group_by_org "$OPENED_PRS")
## PRs Reviewed ($REVIEWED_COUNT)

$(group_by_org "$REVIEWED_PRS")
## Issues/PRs Commented On ($COMMENTED_COUNT)

$(group_by_org "$COMMENTED")
## Issues Closed ($CLOSED_COUNT)

$(group_by_org "$CLOSED_ISSUES")
---

*This report is automatically generated by GitHub Actions on the same schedule as the PR badges update.*
EOF

echo "Activity log generated successfully!"

# Write structured JSON output
# Maps raw gh search results to a compact shape: {number, repo, org, title, url, date, workstream}
# `date` is the field most relevant to that category (mergedAt/createdAt/updatedAt/closedAt) so the
# /workstream/ timeline can place each event on the ruler.
item_filter() {
    local date_field="$1"
    echo "${WORKSTREAM_JQ_DEF} map({number:.number, repo:.repository.nameWithOwner, org:(.repository.nameWithOwner|split(\"/\")[0]), title:.title, url:.url, date:.${date_field}} | . + {workstream: classify_workstream(.repo)})"
}

jq -n \
    --arg start "$NINETY_DAYS_AGO" \
    --arg end "$TODAY" \
    --arg generatedAt "$GENERATED_AT_ISO" \
    --argjson prsMerged "$(echo "$MERGED_PRS" | jq "$(item_filter closedAt)")" \
    --argjson prsOpened "$(echo "$OPENED_PRS" | jq "$(item_filter createdAt)")" \
    --argjson prsReviewed "$(echo "$REVIEWED_PRS" | jq "$(item_filter updatedAt)")" \
    --argjson issuesCommented "$(echo "$COMMENTED" | jq "$(item_filter updatedAt)")" \
    --argjson issuesClosed "$(echo "$CLOSED_ISSUES" | jq "$(item_filter closedAt)")" \
    '{
        period: {start: $start, end: $end},
        generatedAt: $generatedAt,
        metrics: {
            prsMerged: ($prsMerged | length),
            prsOpened: ($prsOpened | length),
            prsReviewed: ($prsReviewed | length),
            issuesCommented: ($issuesCommented | length),
            issuesClosed: ($issuesClosed | length)
        },
        prsMerged: $prsMerged,
        prsOpened: $prsOpened,
        prsReviewed: $prsReviewed,
        issuesCommented: $issuesCommented,
        issuesClosed: $issuesClosed
    }' > "$JSON_OUTPUT_FILE"

echo "Activity JSON generated successfully!"
